"""Add screening_type field to ScreeningResult

Revision ID: 0beb38ffe53c
Revises: f5ed7e38d8a9
Create Date: 2026-03-17 14:17:19.479118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0beb38ffe53c'
down_revision: Union[str, Sequence[str], None] = 'f5ed7e38d8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可以为 NULL 的字段
    op.add_column('screening_results', sa.Column('screening_type', sa.String(length=20), nullable=True, comment='筛选方式: job-岗位筛选, custom-自定义描述筛选'))
    
    # 为现有记录设置默认值
    op.execute("UPDATE screening_results SET screening_type = 'job' WHERE screening_type IS NULL")
    
    # 修改字段为 NOT NULL
    op.alter_column('screening_results', 'screening_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'screening_type')
    # ### end Alembic commands ###
