"""add embedding status fields to resume

Revision ID: 179bbaaf8cf8
Revises: 7a6f6b2c54cd
Create Date: 2026-03-17 00:26:59.831488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179bbaaf8cf8'
down_revision: Union[str, Sequence[str], None] = '7a6f6b2c54cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('embedding_status', sa.String(length=20), nullable=True, comment='embedding 处理状态: pending, processing, completed, failed'))
    op.add_column('resumes', sa.Column('embedding_error', sa.Text(), nullable=True, comment='embedding 处理错误信息'))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'embedding_error')
    op.drop_column('resumes', 'embedding_status')
    # ### end Alembic commands ###
