"""add_job_requirements_fields

Revision ID: 7a6f6b2c54cd
Revises: 9fe1b721c3b5
Create Date: 2026-03-16 23:15:11.207964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6f6b2c54cd'
down_revision: Union[str, Sequence[str], None] = '9fe1b721c3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('experience_years', sa.Integer(), nullable=True, comment='工作经验要求（年）'))
    op.add_column('jobs', sa.Column('education', sa.String(length=50), nullable=True, comment='学历要求'))
    op.add_column('jobs', sa.Column('certifications', sa.Text(), nullable=True, comment='资格证书要求'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'certifications')
    op.drop_column('jobs', 'education')
    op.drop_column('jobs', 'experience_years')
    # ### end Alembic commands ###
