"""add_is_screened_field_to_resume

Revision ID: a2688fd4e9f7
Revises: ff314015d10a
Create Date: 2026-03-19 02:23:10.978484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2688fd4e9f7'
down_revision: Union[str, Sequence[str], None] = 'ff314015d10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_screened', sa.Boolean(), nullable=True, comment='是否已被筛选过'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_screened')
    # ### end Alembic commands ###
