"""add_quota_addons_and_plan_type

Revision ID: b3e308bb3481
Revises: a1b2c3d4e5f6
Create Date: 2026-03-29 22:01:36.860048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e308bb3481'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_addons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False, comment='关联的支付订单ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='购买用户ID'),
    sa.Column('company_id', sa.String(length=50), nullable=True, comment='公司ID（有公司时记录）'),
    sa.Column('addon_resumes', sa.Integer(), nullable=True, comment='额外增加的筛选简历数'),
    sa.Column('addon_jobs', sa.Integer(), nullable=True, comment='额外增加的岗位数'),
    sa.Column('month_key', sa.String(length=7), nullable=False, comment='生效月份（格式: 2026-03）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_quota_addons_company_id'), 'quota_addons', ['company_id'], unique=False)
    op.create_index(op.f('ix_quota_addons_month_key'), 'quota_addons', ['month_key'], unique=False)
    op.create_index(op.f('ix_quota_addons_user_id'), 'quota_addons', ['user_id'], unique=False)
    op.alter_column('payment_orders', 'product_type',
               existing_type=sa.VARCHAR(length=50),
               comment='产品类型: subscription-订阅, addon-加量包',
               existing_comment='产品类型: subscription-订阅, credit-余额充值',
               existing_nullable=False)
    op.alter_column('screening_results', 'deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否已删除（软删除，配额计算仍计入）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('subscription_plans', sa.Column('plan_type', sa.String(length=20), nullable=True, comment='套餐类型: subscription-订阅, addon-加量包'))
    op.add_column('subscription_plans', sa.Column('addon_resumes', sa.Integer(), nullable=True, comment='加量包额外增加的筛选简历数'))
    op.add_column('subscription_plans', sa.Column('addon_jobs', sa.Integer(), nullable=True, comment='加量包额外增加的岗位数'))
    op.alter_column('subscription_plans', 'is_test',
               existing_type=sa.BOOLEAN(),
               comment='是否为测试套餐（仅管理员可见）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'is_test',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为测试套餐（仅管理员可见）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('subscription_plans', 'addon_jobs')
    op.drop_column('subscription_plans', 'addon_resumes')
    op.drop_column('subscription_plans', 'plan_type')
    op.alter_column('screening_results', 'deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已删除（软删除，配额计算仍计入）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('payment_orders', 'product_type',
               existing_type=sa.VARCHAR(length=50),
               comment='产品类型: subscription-订阅, credit-余额充值',
               existing_comment='产品类型: subscription-订阅, addon-加量包',
               existing_nullable=False)
    op.drop_index(op.f('ix_quota_addons_user_id'), table_name='quota_addons')
    op.drop_index(op.f('ix_quota_addons_month_key'), table_name='quota_addons')
    op.drop_index(op.f('ix_quota_addons_company_id'), table_name='quota_addons')
    op.drop_table('quota_addons')
    # ### end Alembic commands ###
