"""add_matching_score_field_to_screening_results

Revision ID: e126070c8b49
Revises: a2688fd4e9f7
Create Date: 2026-03-20 18:47:54.582627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e126070c8b49'
down_revision: Union[str, Sequence[str], None] = 'a2688fd4e9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_results', sa.Column('matching_score', sa.Float(), nullable=True, comment='LLM匹配度评分'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'matching_score')
    # ### end Alembic commands ###
