"""add_job_id_field_to_resume

Revision ID: ff314015d10a
Revises: f651df457b52
Create Date: 2026-03-18 23:28:59.483054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff314015d10a'
down_revision: Union[str, Sequence[str], None] = 'f651df457b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('job_id', sa.String(length=50), nullable=True, comment='关联的岗位ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'job_id')
    # ### end Alembic commands ###
